services:
  - type: web
    name: handwriting-recognition
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn scripts.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    buildFilter:
      paths:
        - requirements.txt
        - scripts/**
        - data/**
        - htr_pipeline/**
        - setup.py
